version: '3'

services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: bemeal-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
volumes:
  neo4j-data:
