name: Build and Push to GitHub Registry
# fixme build all images, maybe look into https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  integration-test:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Integration Tests
        run: docker compose -f test/compose.yaml up --abort-on-container-exit --exit-code-from playwright
      - uses: actions/upload-artifact@v4
        with:
          name: integration-test-report
          path: ./test/test-results/index.html
          retention-days: 10
  build-and-push-image:
    needs: [integration-test]
    strategy:
      matrix:
        component: [ backend, frontend ]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to the Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: paulhatch/semantic-version@v5.4.0
        id: semantic-version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR-${{ matrix.component }})"
          minor_pattern: "(MINOR-${{ matrix.component }})"
          change_path: "${{ matrix.component }}"
          version_format: "v${major}.${minor}.${patch}+${increment}"
          namespace: ${{ matrix.component }}

      - name: Build Docker Image
        id: docker-build
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ matrix.component }}
          load: true

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.docker-build.outputs.imageid }}'
          format: 'table'
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        if: github.ref == 'refs/heads/main'
        uses: docker/metadata-action@v5.5.1
        with:
          images: "${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.component }}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=raw, value=${{ steps.semantic-version.outputs.version }}

      - name: Push Docker Image
        id: docker-push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./${{ matrix.component }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

